# Generated by Django 5.0.6 on 2024-08-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jangapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practice",
            name="date_created",
        ),
    ]
