# Generated by Django 5.0.6 on 2024-08-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jangapp", "0002_remove_practice_date_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=200)),
                ("time_created", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="practice",
        ),
    ]
