# Generated by Django 5.0.6 on 2024-08-16 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jangapp", "0003_posts_delete_practice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="time_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
