# Generated by Django 5.0.6 on 2024-08-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jangapp", "0004_alter_posts_time_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="description",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="posts",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
